services:
  postgres:
    image: postgres_container
    environment:
      - POSTGRES_USER=value
  api:
    build:
      context: .
      target: builder
      dockerfile: ./API/Dockerfile
    container_name: api-fastapi
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"

