services:
  api:
    build:
      context: .
      target: builder
      dockerfile: ./API/Dockerfile
    container_name: api-fastapi
    environment:
      PORT: 8080
    ports:
      - '8080:8080'
    restart: "no"

